version: latest


services:

  nginx:
    container_name: "isasgg_nginx"
    restart: always
    tty: false
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    volumes:
      - ./django/staticfiles:/var/www/public/staticfiles
      - ./django/medias:/var/www/public/medias
    depends_on:
      - django
    networks:
      - isasgg_network

  django:
    container_name: "isasgg_django"
    restart: always
    tty: true
    build:
      context: ./django
      dockerfile: Dockerfile
    volumes:
      - ./django/staticfiles:/var/www/public/staticfiles
      - ./django/medias:/var/www/public/medias
    env_file:
      - "./django/.env"
    depends_on:
      - postgres
      - redis
    networks:
      - isasgg_network

  postgres:
    container_name: "isasgg_postgres"
    restart: always
    tty: false
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - isasgg_network

  adminer:
    container_name: "isasgg_adminer"
    restart: always
    tty: false
    build:
      context: ./adminer
      dockerfile: Dockerfile
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - isasgg_network

  redis:
    container_name: "isasgg_redis"
    restart: always
    tty: false
    build:
      context: ./redis
      dockerfile: Dockerfile
    networks:
      - isasgg_network


volumes:
  postgres-data:


networks:
  isasgg_network:
    driver: bridge